### ISSUE TITLE
No queue stats

### ISSUE THREAD

**Issue by cbrdy** [jjjw420/splunk-ibm-websphere-mq-add-on#1]
Hello,

I'm on IBM MQ 9.1 running on OEL X86_64. I can see channel stats on splunk but the queue stats are none at all. Can you help me if I'm missing anything on my side ?

Thank you

**Comment by cbrdy** [comment]
this is what I'm seeing in splunk log.

03-29-2019 10:39:29.344 -0400 DEBUG ExecProcessor - cmd='python /opt/splunk/etc/apps/mq_ta/bin/mqinput.py' Not added to run queue

**Comment by jjjw420** [comment]
my word.   Never even saw this issue.

When you say "queue stats" - do you want to see number of messages?  or what?  Queue statistics is a bit boring.

The MQ modular input reads messages from queues.  It does not actually write statistics about queues.

Let me know

**Comment by jjjw420** [comment]
Closing issue.   Native "queue" statistic functionality is not provided.   This plugin can be used to read events from IBM MQ queues or for IBM MQ Channel statistics.
