### ISSUE TITLE
Password Optional but Strip Method presents Error in Splunkd.log when left blank

### ISSUE THREAD

**Issue by jay-tb** [jjjw420/splunk-ibm-websphere-mq-add-on#5]
When enabling a "IBM Websphere MQ Channel Status" data input, though the password is not a required field in the form, when submitting the form with it blank, the following error presents itself in the splunkd.log:

> 11-19-2019 13:13:36.822 -0700 INFO  ExecProcessor - Removing status item "/opt/splunk/etc/apps/mq_ta/bin/mqchs.py (mqchs://Test Channel Status) (isModInput=yes)
> 11-19-2019 13:13:39.498 -0700 INFO  ExecProcessor - New scheduled exec process: python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py" Traceback (most recent call last):
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py"   File "/opt/splunk/etc/apps/mq_ta/bin/mqchs.py", line 555, in <module>
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py"     do_run()
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py"   File "/opt/splunk/etc/apps/mq_ta/bin/mqchs.py", line 249, in do_run
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py"     include_zero_values)
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py"   File "/opt/splunk/etc/apps/mq_ta/bin/mqchs.py", line 280, in __init__
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py"     self.mq_password = self.mq_password.encode("ascii").strip()
> 11-19-2019 13:13:39.569 -0700 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/mq_ta/bin/mqchs.py" AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by jjjw420** [comment]
That's bad.   fixing it quick.

**Comment by jjjw420** [comment]
I added default values for the user and password for the channel staus and queue inputs.   
Please check out the latest version and let me know.   (https://github.com/jjjw420/splunk-ibm-websphere-mq-add-on/commit/95a111c897d9f7c344953434ef05974fffbd9910)

I tested with and without auth and with/without a user and password combinations.   Should have done that before - but I've been a bit "happy path" driven with everything going on.  

It feels like I should validate for the password to be present if the user is supplied.   But the current fix is an easy one and you will pick up your auth issues in the log if you send invalid credentials.

**Comment by jay-tb** [comment]
Our IBM MQ Admin states no password is required for client connections, but I've yet to align with them and implement since your latest update.  Will post back with success or failure, and details if the latter.

Thanks again!

**Comment by jjjw420** [comment]
No problem.   All the combinations seem to work.

**Comment by jay-tb** [comment]
Looks like this worked and we were able to successfully connect and read a message off a Queue, however it took the message off of the queue, which would prevent the actual systems processing.

Received another error related to stats - will open an issue accordingly.

Thanks again for your responsiveness on this fix!
